version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build: .
    container_name: spring-boot-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
